name: EduVista CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Frontend
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci

      - name: Build React Application
        working-directory: frontend
        run: npm run build

      # Backend
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      # Docker
      - name: Build Frontend Docker Image
        working-directory: frontend
        run: docker build -t eduvista-frontend:${{ github.sha }} .

      - name: Build Backend Docker Image
        working-directory: backend
        run: docker build -t eduvista-backend:${{ github.sha }} .
